# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: build
      run: | 
        npm install
        cd scripts/now
        node build
    - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.NOW_TOKEN }} # Required
          #now-args: '--prod' #Optional
          now-org-id: ${{ secrets.NOW_ORG_ID}}  #Required
          now-project-id: ${{ secrets.NOW_PROJECT_ID}} #Required 
          working-directory: ./scripts/now
      #run: npm run deploy:now -- -- --token ${{ secrets.NOW_TOKEN }}
